package com.bot.screenshoter.constants;

public enum InlineButtonEnum {

    SIMPLE_SCREENSHOT_BUTTON,
    LONG_SCREENSHOT_BUTTON,
    SET_UP_CUSTOM_SCREENSHOT_BUTTON,
    TAKE_CUSTOM_SCREENSHOT_BUTTON,

    CONFIRM_BUTTON,
    CANCEL_BUTTON,

    RUSSIA_LANG_BUTTON,
    ENGLISH_LANG_BUTTON
}
