package com.bot.screenshoter.constants;

public enum InlineButtonEnum {

    SIMPLE_SCREENSHOT_BUTTON,
    LONG_SCREENSHOT_BUTTON,
    CUSTOM_SCREENSHOT_BUTTON,

    CONFIRM_CUSTOM_SCREENSHOT_BUTTON,
    CANCEL_BUTTON,

    RUSSIA_LANG_BUTTON,
    ENGLISH_LANG_BUTTON
}
