telegram:
  webhook-path:
  bot-username:
  bot-token:

spring:
  datasource:
    url:
    username:
    password:
  output:
    ansi:
      enabled: "always"

logging:
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS,Asia/Yekaterinburg"
  level:
    root: "INFO"

